//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//


package com.mobiera.lib.etsi102225.api.model;

import javax.xml.bind.annotation.XmlRegistry;



@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.tapublog.lib.gsm0348.api.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CardProfile }
     * 
     */
    public CardProfile createCardProfile() {
        return new CardProfile();
    }

    /**
     * Create an instance of {@link SPI }
     * 
     */
    public SPI createSPI() {
        return new SPI();
    }

    /**
     * Create an instance of {@link CommandPacket }
     * 
     */
    public CommandPacket createCommandPacket() {
        return new CommandPacket();
    }

    /**
     * Create an instance of {@link KIC }
     * 
     */
    public KIC createKIC() {
        return new KIC();
    }

    /**
     * Create an instance of {@link CommandSPI }
     * 
     */
    public CommandSPI createCommandSPI() {
        return new CommandSPI();
    }

    /**
     * Create an instance of {@link SecurityHeader }
     * 
     */
    public SecurityHeader createSecurityHeader() {
        return new SecurityHeader();
    }

    /**
     * Create an instance of {@link Packet }
     * 
     */
    public Packet createPacket() {
        return new Packet();
    }

    /**
     * Create an instance of {@link ResponsePacket }
     * 
     */
    public ResponsePacket createResponsePacket() {
        return new ResponsePacket();
    }

    /**
     * Create an instance of {@link KID }
     * 
     */
    public KID createKID() {
        return new KID();
    }

    /**
     * Create an instance of {@link ResponseSPI }
     * 
     */
    public ResponseSPI createResponseSPI() {
        return new ResponseSPI();
    }

    /**
     * Create an instance of {@link ResponsePacketHeader }
     * 
     */
    public ResponsePacketHeader createResponsePacketHeader() {
        return new ResponsePacketHeader();
    }

    /**
     * Create an instance of {@link PacketHeader }
     * 
     */
    public PacketHeader createPacketHeader() {
        return new PacketHeader();
    }

    /**
     * Create an instance of {@link CommandPacketHeader }
     * 
     */
    public CommandPacketHeader createCommandPacketHeader() {
        return new CommandPacketHeader();
    }

}
